---

- name: Add universe repo
  apt_repository:
    repo: deb http://ch.archive.ubuntu.com/ubuntu/ bionic universe
    state: present

- name: Add multiverse repo
  apt_repository:
    repo: deb http://ch.archive.ubuntu.com/ubuntu/ bionic multiverse
    state: present

- name: Update APT package cache
  apt:
    update_cache: true
    cache_valid_time: 3600
  tags:
    - apt

- name: Upgrade APT to the latest packages
  apt:
    upgrade: safe

- name: Install Cuckoo dependencies
  apt:
    state: present
    pkg: "{{item}}"
  with_items:
    - "{{cuckoo_required_packages}}"
  tags:
    - requirements

- name: Install KVM
  apt:
    state: present
    pkg: "{{item}}"
  with_items:
    - "{{cuckoo_kvm_packages}}"
  tags:
    - kvm

- name: Install tcpdump
  apt: 
    state: present    
    pkg: "{{item}}"
  with_items:
    - "{{cuckoo_tcpdump_packages}}"
  tags:
    - tcpdump

- name: Disable AppArmor for tcpdump
  command: aa-disable /usr/sbin/tcpdump
  args:
    creates: /etc/apparmor.d/disable/usr.sbin.tcpdump
  tags: 
    - tcpdump

- name: Set tcpdump capabilities
  command: setcap cap_net_raw,cap_net_admin=eip /usr/sbin/tcpdump
  tags: 
    - tcpdump
